image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_release:
  stage: build
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --build-arg GAME_GIT_HASH="${CI_COMMIT_SHA}"
      --build-arg GAME_GIT_HASH_SHORT="${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_TAG && ($CI_COMMIT_BRANCH == "release" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

build_manually:
  stage: build
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --build-arg GAME_GIT_HASH="${CI_COMMIT_SHA}"
      --build-arg GAME_GIT_HASH_SHORT="${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_TAG
