"""Add Level position attrib

Revision ID: 1745256339
Revises: 1743941273
Create Date: 2025-04-21 19:25:39.591484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1745256339'
down_revision: Union[str, None] = '1743941273'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('levelPosition', sa.Integer(), nullable=False, server_default="-2"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'levelPosition')
    # ### end Alembic commands ###
